### ISSUE TITLE
Should restore initial package state, which might not match Pkg.free on everything

### ISSUE THREAD

**Issue by tkelman** [bramtayl/RequirementVersions.jl#2]
This could be a bit tricky. I tend to do these things in a temporary JULIA_PKGDIR to avoid messing with the usual package dir. But you do have to get the package-under-test installed there, and make sure it's at the version you care about testing. `Pkg.free.(requirements)` could leave things in a different state than they started, which might be a bit surprising side effect from `Pkg.test("RequirementVersions")` or manual usage.

**Comment by bramtayl** [comment]
Huh

**Comment by bramtayl** [comment]
Seems like there must be an easier way to do this. Like Pkg.save and Pkg.restore? Useful functions to have around if they don't exist

**Comment by bramtayl** [comment]
My understanding is this is all going to become a waste of time once Pkg3 hits so it might be worth just waiting a bit.

**Comment by bramtayl** [comment]
Could I simply make copies of the repositories to be modified in a separate folder, run everything, then overwrite the modified repos?

**Comment by tkelman** [comment]
that might work

**Comment by bramtayl** [comment]
Should be fixed by most recent commit.

**Comment by tkelman** [comment]
Yep.

Separate issue, should fill in the package description to something more specific than "No description, website, or topics provided."

**Comment by tkelman** [comment]
Oh, I think it'll need to archive and restore the top-level REQUIRE file from the package directory too

**Comment by bramtayl** [comment]
Oh no why? PS added a description

**Comment by tkelman** [comment]
Guess not actually, since it looks like Pkg.pin (or your local version) works by checking out a git branch rather than setting bounds in the top-level REQUIRE file.
