### ISSUE TITLE
should_resolve

### ISSUE THREAD

**Issue by tkelman** [bramtayl/RequirementVersions.jl#3]
Why were you disabling this? This means some of the Pkg.test errors will come from dependencies that should actually get downgraded when you use an old enough version of a requirement that you're testing against. I saw this for example when sweeping StatsBase on something, using pre-0.15.0 should have downgraded DataArrays even if the package being tested doesn't use anything that requires 0.15.0.

**Comment by tkelman** [comment]
Another example seen with Distances, if old versions of a package have dependencies (here ArrayViews) that recent versions don't depend on, not resolving makes that dependency break for a reason unrelated to the package being tested.

**Comment by bramtayl** [comment]
I had to to get travis tests to pass. Any time resolve was called it started removing packages it wasn't supposed to.

**Comment by bramtayl** [comment]
See for example https://travis-ci.org/bramtayl/RequirementVersions.jl/jobs/264387199

**Comment by tkelman** [comment]
That version of NumberedLines doesn't depend on MacroTools - https://github.com/bramtayl/NumberedLines.jl/blob/v0.0.3/REQUIRE. It's probably just a bad interaction between Pkg.test of this package vs later resolves not seeing the test dependency. Testing against manually-added ChainRecursive in a temporary JULIA_PKGDIR would probably work better than using test/REQUIRE for this

**Comment by bramtayl** [comment]
I don't understand...

**Comment by tkelman** [comment]
Travis runs `Pkg.test("RequirementVersions")` which adds ChainRecursive temporarily. If running `minimum_requirement_versions("ChainRecursive")` then does a `Pkg.resolve()`, it is allowed to remove things ChainRecursive depends on and possibly remove ChainRecursive itself. So `minimum_requirement_versions` can't / shouldn't be run against packages that are only installed as test dependencies.

**Comment by bramtayl** [comment]
So if I moved ChainRecursive from test/REQUIRE to REQUIRE and reenabled version resolution the tests would pass?

**Comment by tkelman** [comment]
Bit of a guess, but I think so
